Solution module2
js-tasks-ru/jsbasic-20230302_natalinebo2014 pull request #4
Opened 2023-03-12 14:02 UTC by NataliItaly

2023-03-12 14:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-14 11:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-03-14 21:13 UTC, SinimaWath requested changes

2023-03-14 21:13 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Тут надо использовать функцию map

2023-03-14 21:13 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return arr.join("").split("-").join("");
Давай попробуем переписать через:
```
return str.split('-').map(() => ....).join('')
```

2023-03-14 21:13 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    .join("\n");
Давай перепишем на:
```
users.filter(....).map(....).join('\n')
```

2023-03-15 21:19 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-16 16:20 UTC, SinimaWath approved these changes

2023-03-16 16:21 UTC, merged